
variables:
  GO_SEMANTIC_RELEASE_VERSION: 2.12.0

  # Note, GOLANGCI_LINT_VERSION should match .tool-versions!
  GOLANGCI_LINT_VERSION: 1.41.1

include:
  # We cannot use mergrequest pipeline workflows for chef-repo because
  # we need to run pipelines on the ops.gitlab.net mirror
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

image: golang:1.16

stages:
  - check
  - check_remote
  - test
  - build
  - release

format:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...
    - go test -race ./...

compile:
  stage: build
  script:
    - go build .

commitlint:
  stage: test
  image: node:14-alpine3.12
  before_script:
  - apk add --no-cache git
  - npm install
  script:
  - npx commitlint --from ${CI_MERGE_REQUEST_TARGET_BRANCH_SHA} --to HEAD --verbose
  rules:
  - if: $CI_MERGE_REQUEST_IID

release:
  image: node:14
  stage: release
  script:
    - npm install
    - $(npm bin)/semantic-release

##############
# Conditions #
##############

.if-mirror: &if-mirror
  if: "$MIRROR == \"true\""

.if-canonical: &if-canonical
  if: "$CANONICAL == \"true\""

# Uses Woodhouse (https://gitlab.com/gitlab-com/gl-infra/woodhouse) notification subcommand to add a MR comment on the canonical repository. See CONTRIBUTE.md#project-workflow for more information.
notify_mirror_source:
  allow_failure: true
  rules:
    - <<: *if-mirror
  image: "registry.gitlab.com/gitlab-com/gl-infra/woodhouse:latest"
  script: woodhouse gitlab notify-mirrored-mr
  stage: check

check_remote:
  stage: check_remote
  image: "registry.gitlab.com/gitlab-com/gl-infra/woodhouse:latest"
  script: woodhouse gitlab follow-remote-pipeline --gitlab-api-base-url="https://ops.gitlab.net/api/v4" --gitlab-api-token="$OPS_API_TOKEN"
  rules:
    - <<: *if-canonical

