# DO NOT MANUALLY EDIT; Run ./bin/update-asdf-version-variables to update this
variables:
    ASDF_GOLANG_VERSION: 1.17.5
    ASDF_GOLANG_MAJOR_VERSION: 1
    ASDF_GOLANGCI_LINT_VERSION: 1.43.0
    ASDF_GOLANGCI_LINT_MAJOR_VERSION: 1
    ASDF_GORELEASER_VERSION: 1.2.2
    ASDF_GORELEASER_MAJOR_VERSION: 1
    ASDF_NODEJS_VERSION: 16.13.1
    ASDF_NODEJS_MAJOR_VERSION: 16
