
variables:
  GO_SEMANTIC_RELEASE_VERSION: 2.12.0

  # Note, GOLANGCI_LINT_VERSION should match .tool-versions!
  GOLANGCI_LINT_VERSION: 1.41.1

include:
  # We cannot use mergrequest pipeline workflows for chef-repo because
  # we need to run pipelines on the ops.gitlab.net mirror
  - template: 'Workflows/Branch-Pipelines.gitlab-ci.yml'

image: golang:1.16

stages:
  - check
  - check_remote
  - test
  - build
  - release

format:
  stage: test
  script:
    - go fmt ./...
    - go vet ./...
    - go test -race ./...

compile:
  stage: build
  script:
    - go build .

commitlint:
  stage: test
  image: node:14-alpine3.12
  before_script:
  - apk add --no-cache git
  - npm install
  script:
  - npx commitlint --from ${CI_MERGE_REQUEST_TARGET_BRANCH_SHA} --to HEAD --verbose
  rules:
  - if: $CI_MERGE_REQUEST_IID

semantic_release:
  image: node:14
  stage: release
  script:
    - npm install
    - $(npm bin)/semantic-release

release:
  stage: release
  image: docker:stable
  services:
    - docker:dind
  variables:
    DOCKER_REGISTRY: $CI_REGISTRY
    DOCKER_USERNAME: $CI_REGISTRY_USER
    DOCKER_PASSWORD: $CI_REGISTRY_PASSWORD

    # Disable shallow cloning so that goreleaser can diff between tags to
    # generate a changelog.
    GIT_DEPTH: 0

  # Only run this release job for tags, not every commit (for example).
  # only:
  #   refs:
  #     - tags

  script: |
    # GITLAB_TOKEN is needed to create GitLab releases.
    # DOCKER_* are needed to push Docker images.
    docker run --rm --privileged \
      -v $PWD:$PWD \
      -w $PWD \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -e DOCKER_USERNAME -e DOCKER_PASSWORD -e DOCKER_REGISTRY  \
      -e GITLAB_TOKEN \
      goreleaser/goreleaser release --rm-dist

##############
# Conditions #
##############

.if-mirror: &if-mirror
  if: "$MIRROR == \"true\""

.if-canonical: &if-canonical
  if: "$CANONICAL == \"true\""

# Uses Woodhouse (https://gitlab.com/gitlab-com/gl-infra/woodhouse) notification subcommand to add a MR comment on the canonical repository. See CONTRIBUTE.md#project-workflow for more information.
notify_mirror_source:
  allow_failure: true
  rules:
    - <<: *if-mirror
  image: "registry.gitlab.com/gitlab-com/gl-infra/woodhouse:latest"
  script: woodhouse gitlab notify-mirrored-mr
  stage: check

check_remote:
  stage: check_remote
  image: "registry.gitlab.com/gitlab-com/gl-infra/woodhouse:latest"
  script: woodhouse gitlab follow-remote-pipeline --gitlab-api-base-url="https://ops.gitlab.net/api/v4" --gitlab-api-token="$OPS_API_TOKEN"
  rules:
    - <<: *if-canonical

