# DO NOT MANUALLY EDIT; Run ./scripts/update-asdf-version-variables.sh to update this
variables:
    GL_ASDF_GOLANG_VERSION: "1.21.6"
    GL_ASDF_GOLANGCI_LINT_VERSION: "1.56.2"
    GL_ASDF_GORELEASER_VERSION: "1.23.0"
    GL_ASDF_PRE_COMMIT_VERSION: "3.6.1"
    GL_ASDF_SHELLCHECK_VERSION: "0.9.0"
    GL_ASDF_SHFMT_VERSION: "3.8.0"
