before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

# dockers:
#   - image_templates:
#     - "gitlab-com/gl-infra/jsonnet-tool:latest"
#     - "gitlab-com/gl-infra/jsonnet-tool:{{ .Tag }}"
#     - "gitlab-com/gl-infra/jsonnet-tool:v{{ .Major }}"
#     goos: linux
#     goarch: amd64

release:
  gitlab:
    name: 28085261

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
