before:
  hooks:
    - go mod tidy
builds:
  - id: "jsonnet-tool"
    binary: "jsonnet-tool"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X '{{.ModulePath}}/cmd.version={{.Version}}' -X '{{.ModulePath}}/cmd.commit={{.Commit}}' -X '{{.ModulePath}}/cmd.date={{.Date}}'

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64

dockers:
  - image_templates:
    - "{{ .Env.CI_REGISTRY_IMAGE }}:latest"
    - "{{ .Env.CI_REGISTRY_IMAGE }}:{{ .Tag }}"
    - "{{ .Env.CI_REGISTRY_IMAGE }}:v{{ .Major }}"
    goos: linux
    goarch: amd64

release:
  gitlab:
    name: 28085261

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
