before:
  hooks:
    - go mod tidy
builds:
  - binary: "jsonnet-tool"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X '{{.ModulePath}}/cmd.version={{.Version}}' -X '{{.ModulePath}}/cmd.commit={{.Commit}}' -X '{{.ModulePath}}/cmd.date={{.Date}}'

archives:
  - id: jsonnet-tool
    builds:
      - jsonnet-tool
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

dockers:
  - id: jsonnet-tool
    ids:
      - jsonnet-tool
    image_templates:
      - "{{ .Env.CI_REGISTRY_IMAGE }}:latest"
      - "{{ .Env.CI_REGISTRY_IMAGE }}:{{ .Tag }}"
    goos: linux
    goarch: amd64

release:
  gitlab:
    owner: gitlab-com/gl-infra
    name: "jsonnet-tool"
  mode: append

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: gitlab
  filters:
    exclude:
      - '^test\b'
      - '^ci\b'

gitlab_urls:
  api: "{{ .Env.CI_SERVER_URL }}"
  download: "{{ .Env.CI_SERVER_URL }}"
